### ISSUE TITLE
get_commensurate_diagonal_supercell returns 0 on diagonal

### ISSUE THREAD

**Issue by xivh** [phonopy/spgrep-modulation#15]
The get_commensurate_diagonal_supercell function can return zeros on the diagonal:

>>> get_commensurate_diagonal_supercell([0.25, 0.25, 0.25])
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

My attemped fix is in #14 

>>> get_commensurate_diagonal_supercell([0.25, 0.25, 0.25])
array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

**Comment by lan496** [comment]
Fixed: https://github.com/phonopy/spgrep-modulation/pull/14
